import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
const formatRating = (rating) => rating.toFixed(1);
const ShopCard = ({ shop }) => {
    const phoneHref = `tel:${shop.contact.phoneNumber}`;
    const whatsappNumber = shop.contact.whatsappNumber ?? shop.contact.phoneNumber;
    const whatsappHref = `https://wa.me/${whatsappNumber.replace(/[^+\d]/g, "")}`;
    return (_jsxs("article", { className: "group flex flex-col overflow-hidden rounded-3xl bg-white/90 shadow-card transition hover:-translate-y-1 hover:shadow-lg", children: [_jsxs("div", { className: "relative h-48 overflow-hidden", children: [_jsx("img", { alt: shop.name, src: shop.imageUrl, className: "h-full w-full object-cover transition duration-500 group-hover:scale-105" }), _jsx("span", { className: "absolute left-4 top-4 rounded-full bg-white/80 px-3 py-1 text-xs font-semibold text-secondary", children: shop.tags?.[0] ?? "Featured" })] }), _jsxs("div", { className: "flex flex-1 flex-col gap-4 p-6", children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-display text-lg font-semibold text-secondary", children: shop.name }), _jsx("p", { className: "text-sm text-secondary/70", children: shop.location.address })] }), _jsxs("div", { className: "rounded-full bg-primary/10 px-3 py-1 text-sm font-semibold text-primary", children: ["\u2B50 ", formatRating(shop.rating)] })] }), _jsx("p", { className: "line-clamp-2 text-sm text-secondary/80", children: shop.description }), typeof shop.location.distanceKm === "number" && (_jsxs("p", { className: "text-sm font-medium text-secondary", children: ["\uD83D\uDCCD ", shop.location.distanceKm.toFixed(1), " km away"] })), _jsxs("div", { className: "mt-auto flex flex-wrap gap-3", children: [_jsx("a", { href: phoneHref, className: "inline-flex flex-1 items-center justify-center gap-2 rounded-full border border-primary px-4 py-2 font-semibold text-primary transition hover:bg-primary hover:text-white", children: "\uD83D\uDCDE Call" }), _jsx("a", { href: whatsappHref, target: "_blank", rel: "noreferrer", className: "inline-flex flex-1 items-center justify-center gap-2 rounded-full bg-green-500 px-4 py-2 font-semibold text-white transition hover:bg-green-600", children: "\uD83D\uDCAC WhatsApp" })] }), _jsx(Link, { to: `/shops/${shop.id}`, className: "mt-2 inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline", children: "View details \u2192" })] })] }));
};
export default ShopCard;
